"""
3D Conformation Generation and DFT Input Preparation.
Uses RDKit ETKDG and MMFF to generate 3D conformers and create ORCA input files.

Reference: https://github.com/rangsimanketkaew/mlff
"""

import argparse
import os
import sys
from rdkit import Chem
from rdkit.Chem import AllChem

def generate_conformers(smiles, num_conformers=10):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Invalid SMILES string: {smiles}")
        
    mol = Chem.AddHs(mol)
    
    print(f"Embedding {num_conformers} conformers using ETKDG...")
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    conformer_ids = AllChem.EmbedMultipleConfs(mol, numConfs=num_conformers, params=params)
    
    if len(conformer_ids) == 0:
        raise RuntimeError("Conformer embedding failed. Check molecule structure.")
        
    print("Optimizing conformers with MMFF94 force field...")
    ff_properties = AllChem.MMFFGetMoleculeProperties(mol)
    results = AllChem.MMFFOptimizeMoleculeConfs(mol, numThreads=0)
    
    best_conf_id = -1
    min_energy = float('inf')
    
    for conf_id, (converged, energy) in enumerate(results):
        if converged == 0 and energy < min_energy:
            min_energy = energy
            best_conf_id = conf_id
            
    if best_conf_id == -1:
        best_conf_id = conformer_ids[0]
        print("Warning: MMFF optimization did not converge. Using unoptimized conformer.")
    else:
        print(f"Lowest energy conformer found: ID {best_conf_id} (Energy: {min_energy:.2f} kcal/mol)")
        
    return mol, best_conf_id

def write_orca_input(mol, conf_id, output_path, orca_header="! rKS B3LYP Def2-SVP Opt Freq"):
    conformer = mol.GetConformer(conf_id)
    
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else '.', exist_ok=True)
    
    with open(output_path, "w") as f:
        f.write(f"# ORCA input generated by congenerate_dft.py\n")
        f.write(f"{orca_header}\n\n")
        f.write("* xyz 0 1\n")
        
        for atom in mol.GetAtoms():
            symbol = atom.GetSymbol()
            pos = conformer.GetAtomPosition(atom.GetIdx())
            f.write(f"  {symbol:<4} {pos.x:12.6f} {pos.y:12.6f} {pos.z:12.6f}\n")
            
        f.write("*\n")
        
    print(f"Successfully wrote ORCA input file to: {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Conformation Generation & DFT Input Deck Setup")
    parser.add_argument("--smiles", type=str, default="CC(=O)O", help="SMILES string of target molecule")
    parser.add_argument("--num_conformers", type=int, default=5, help="Number of conformers to embed")
    parser.add_argument("--output", type=str, default="orca_job.inp", help="Output path for ORCA file")
    parser.add_argument("--method", type=str, default="! rKS B3LYP Def2-SVP Opt Freq", help="ORCA calculation header keywords")
    
    args = parser.parse_args()
    
    try:
        mol, best_conf_id = generate_conformers(args.smiles, args.num_conformers)
        write_orca_input(mol, best_conf_id, args.output, args.method)
    except Exception as e:
        print(f"Execution failed: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
